version: "3.8"

services:
  webots:
    build:
      context: simulation
      dockerfile: Dockerfile
      args:
        - WEBOTS_DEFAULT_IMAGE=$IMAGE
    command: webots --stream="port=$PORT;monitorActivity" --batch --mode=realtime --minimize --no-rendering /webots_project/worlds/e-puck.wbt
    environment:
      - DISPLAY=:0
    ports:
      - '$PORT:$PORT'
    privileged: true
    stdin_open: true  # docker run -i
    tty: true         # docker run -t
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # - var-$PORT:/var
